apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base  

images:
  - name: hello-java
    #newName: docker.io/123l/hello-world-https
    newName: quay-tjzlj.apps.cluster-tjzlj.tjzlj.sandbox5438.opentlc.com/quayadmin/repo-workshop
    newTag: 1.0.1