apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base  

images:
  - name: hello-java
    #newName: docker.io/123l/hello-world-https
    newName: quay-pljs7.apps.cluster-pljs7.pljs7.sandbox2677.opentlc.com/quayadmin/repo-workshop
    newTag: 1.0.0