---
- name: Convert
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    convert2rhel_repofile_url: "https://cdn-public.redhat.com/content/public/repofiles/convert2rhel-for-rhel-9-x86_64.repo"
    rhsm_org: 14639027
    rhsm_activation_key: 58de7d4b-9d31-4ca4-9138-6d8b16e74db8
    convert_reboot_requested: true
    convert2rhel_analyze: false
    convert2rhel_sslverify: false
    rhsm_username: ""
    rhsm_password: ""
  tasks:
    - name: Perform OS conversion
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert
      
...