# playbooks/glpi-workflow-snapshot-update.yml
---
- name: "GLPI Workflow | Job 2 — Snapshot e Update"
  hosts: localhost
  gather_facts: false
  roles:
    - role: glpi_openshift_correcao
      vars:
        glpi_exec_mode: "snapshot_e_update"