---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pipeline
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache
  namespace: hello-pipeline
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: hello-pipeline
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "BASE64(username:token)"
        }
      }
    }
# Gere o base64: echo -n 'usuario:token' | base64
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: hello-pipeline
secrets:
  - name: docker-hub-secret
