apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-java
  namespace: hello-pipeline
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image-name
      type: string
      description: "ex: docker.io/seuusuario/hello-java"
    - name: image-tag
      type: string
      description: "Versão da imagem: v1, v2, v3..."
  workspaces:
    - name: source
    - name: maven-cache
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source

    - name: build
      taskRef:
        name: maven
      params:
        - name: goals
          value: ["clean","package","-DskipTests=false"]
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: maven-cache
      runAfter:
        - clone

    - name: image
      taskRef:
        name: buildah
      params:
        - name: image
          value: $(params.image-name):$(params.image-tag)
        - name: dockerfile
          value: ./Dockerfile
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - build
