apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm-lucas
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: centos
    argocd.argoproj.io/sync-wave: "2"
  namespace: virt-manage
spec:
  source:
    registry:
      url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  storage:
    resources:
      requests:
        storage: 30Gi
