apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: fedora
    argocd.argoproj.io/sync-wave: "2"
  namespace: virt-manage
spec:
  source:
    registry:
      url: https://dl.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
  storage:
    resources:
      requests:
        storage: 30Gi
