---
- name: Monitorar URL e reiniciar httpd se cair
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        url: "https://app-linuxvm.apps.cluster-k4x6j.dynamic.redhatworkshops.io/"
        method: GET
        verify_ssl: false
        interval: 1         
        
  rules:
    - name: URL fora do ar - reiniciar httpd
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Restart HTTPD"
          organization: "Default"