---
- name: Monitorar URL e reiniciar httpd se cair
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls: 
         - https://vm-linuxvm.apps.cluster-wm967.dynamic.redhatworkshops.io
        delay: 5         
        
  rules:
    - name: URL fora do ar - reiniciar httpd
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Restart HTTPD"
          organization: "Default"