---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-color
  name: webapp-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-color
  template:
    metadata:
      labels:
        app: webapp-color
    spec:
      containers:
        - name: webapp-color
          image: docker.io/kodekloud/webapp-color:latest
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: "1"
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_COLOR
              value: blue