---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-color
  name: webapp-color
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: webapp-color
